#! /usr/bin/env zsh

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ,,="cd $OLDPWD"
alias sudo="sudo "
alias md="mkdir -p"
alias xx="exit"
alias rm="rm -fr"
alias cp="cp -r"
alias ls="eza --color=always --icons --sort=Extension --group-directories-first"
alias l="ls"
alias la="ls --all"
alias ll='ls --long --header --group --time-style="+%d/%m/%y %H:%M" --octal-permissions --extended'
alias ll='ls --long --header --group --octal-permissions --extended'
alias lla="ll -a"
alias tree="ls --tree"
alias t="tree"
alias ta="tree -a"
alias nvim="nvim -o"
alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias stat="grc stat"
alias ping="__ping"
alias w="grc w"
alias lsblk="grc lsblk -o NAME,MODEL,PATH,LABEL,FSTYPE,FSSIZE,FSUSE%,MOUNTPOINT"
alias df="grc df -h"
alias du="grc du -h"
alias env="grc env"
alias iptables="sudo grc iptables"
alias lspci="grc lspci"
alias mysql="mariadb"
alias ip="ip --color=always --pretty"
